### ISSUE TITLE
chrome plugin

### ISSUE THREAD

**Issue by defconparties** [gsugar87/SWCheckIn#1]
Can I run that under linux?

**Comment by gsugar87** [comment]
I have not tested it but it should work.  You just need to download the appropriate Chromedriver for selenium to work.  http://chromedriver.storage.googleapis.com/index.html?path=2.22/ has the 32 and 64 bit Linux versions.  Just download the appropriate version and unzip it.

On line 15 in the checkin.py file, change CHROME_DRIVER_PATH to the full path of the unzipped chromedriver.  I updated the readme to hopefully be more clear.  Let me know how it goes!
